# Site settings
title: "Sean Cho Ayres"
name: "Dr. Sean Cho A."
description: "Poet | AI Ethicist | Professor | Editor"
url: "https://seanchoa.com"
baseurl: ""  # Leave blank for root-level hosting

# Theme and plugins
remote_theme: academicpages/academicpages.github.io

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
  - jekyll-paginate
  - jekyll-redirect-from

# Author sidebar info
author:
  name: "Sean Cho Ayres"
  avatar: "seanprofile.png"  # Must be placed in /images/
  bio: "Poet | AI Ethicist | Professor"
  email: "sayres4@kennesaw.edu"
  location: "Earth"
  employer: "Kennesaw State University"

# Output and page inclusion
include:
  - _pages

permalink: /:title/
markdown: kramdown
highlighter: rouge
excerpt_separator: "\n\n"

# Defaults for page layout and sidebar
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true

